import copy
import logging

import numpy as np

from .polar import Polar

logger = logging.getLogger(__name__)


class Airfoil:
    """Airfoil class with multiple polars."""

    def __init__(self, polars):
        """Constructor for Airfoil."""
        # sort by Reynolds number
        self.polars = sorted(polars, key=lambda p: p.Re)

        # save type of polar we are using
        self.polar_type = polars[0].__class__

    @classmethod
    def initFromAerodynFile(cls, aerodynFile, polarType=Polar):
        """Construct from AeroDyn file."""
        logger.info(f"Loading airfoil file: {aerodynFile}")
        # initialize
        polars = []

        # open aerodyn file
        f = open(aerodynFile)

        # skip through header
        f.readline()
        f.readline().rstrip()  # remove newline
        f.readline()
        numTables = int(f.readline().split()[0])

        # loop through tables
        for _i in range(numTables):
            # read Reynolds number
            Re = float(f.readline().split()[0]) * 1e6

            # read Aerodyn parameters
            param = [0] * 8
            for j in range(8):
                param[j] = float(f.readline().split()[0])

            alpha = []
            cl = []
            cd = []
            cm = []

            # read polar information line by line
            while True:
                line = f.readline()
                if "EOT" in line:
                    break
                data = [float(s) for s in line.split()]
                if len(data) < 4:
                    raise ValueError(f"Error: Expected 4 columns of data but found, {data}")

                alpha.append(data[0])
                cl.append(data[1])
                cd.append(data[2])
                cm.append(data[3])

            polars.append(polarType(Re, alpha, cl, cd, cm))

        f.close()

        return cls(polars)

    def getPolar(self, Re):
        """Get polar at Reynolds number."""
        p = self.polars

        if Re <= p[0].Re:
            return copy.deepcopy(p[0])

        elif Re >= p[-1].Re:
            return copy.deepcopy(p[-1])

        else:
            Relist = [pp.Re for pp in p]
            i = np.searchsorted(Relist, Re)
            weight = (Re - Relist[i - 1]) / (Relist[i] - Relist[i - 1])
            return p[i - 1].blend(p[i], weight)

    def blend(self, other_airfoil, blend_weight):
        """Blend with another airfoil."""
        # combine Reynolds numbers
        Relist1 = [p.Re for p in self.polars]
        Relist2 = [p.Re for p in other_airfoil.polars]
        Relist = np.union1d(Relist1, Relist2)

        # blend polars
        n = len(Relist)
        polars = [0] * n
        for i in range(n):
            p1 = self.getPolar(Relist[i])
            p2 = other_airfoil.getPolar(Relist[i])
            polars[i] = p1.blend(p2, blend_weight)

        return Airfoil(polars)

    def correction3D(
        self,
        radial_position_ratio,
        chord_to_radius_ratio,
        tip_speed_ratio,
        alpha_max_corr=30,
        alpha_linear_min=-5,
        alpha_linear_max=5,
    ):
        """Apply 3-D corrections."""
        n = len(self.polars)
        polars = [0] * n
        for idx, p in enumerate(self.polars):
            polars[idx] = p.correction3D(
                radial_position_ratio,
                chord_to_radius_ratio,
                tip_speed_ratio,
                alpha_max_corr,
                alpha_linear_min,
                alpha_linear_max,
            )

        return Airfoil(polars)

    def extrapolate(self, max_cd, aspect_ratio=None, min_cd=0.001):
        """Extrapolate polars."""
        n = len(self.polars)
        polars = [0] * n
        for idx, p in enumerate(self.polars):
            polars[idx] = p.extrapolate(max_cd, aspect_ratio, min_cd)

        return Airfoil(polars)

    def interpToCommonAlpha(self, alpha=None):
        """Interpolate to common alpha."""
        if alpha is None:
            # union of angle of attacks
            alpha = []
            for p in self.polars:
                alpha = np.union1d(alpha, p.alpha)

        # interpolate each polar to new alpha
        n = len(self.polars)
        polars = [0] * n
        for idx, p in enumerate(self.polars):
            cl = np.interp(alpha, p.alpha, p.cl)
            cd = np.interp(alpha, p.alpha, p.cd)
            cm = np.interp(alpha, p.alpha, p.cm)
            polars[idx] = self.polar_type(p.Re, alpha, cl, cd, cm)

        return Airfoil(polars)

    def writeToAerodynFile(self, filename):
        """Write to AeroDyn file."""
        # aerodyn and wtperf require common set of angles of attack
        af = self.interpToCommonAlpha()

        f = open(filename, "w")

        f.write("AeroDyn airfoil file.")
        f.write("Compatible with AeroDyn v13.0.")
        f.write("Generated by airfoilprep.py")
        f.write("{:<10d}		{:40}".format(len(af.polars), "Number of airfoil tables in this file"))
        for p in af.polars:
            f.write("{:<10f}	{:40}".format(p.Re / 1e6, "Reynolds number in millions."))
            param = p.unsteadyparam()
            f.write("{:<10f}	{:40}".format(param[0], "Control setting"))
            f.write("{:<10f}	{:40}".format(param[1], "Stall angle (deg)"))
            f.write("{:<10f}	{:40}".format(param[2], "Angle of attack for zero Cn for linear Cn curve (deg)"))
            f.write("{:<10f}	{:40}".format(param[3], "Cn slope for zero lift for linear Cn curve (1/rad)"))
            f.write(
                "{:<10f}	{:40}".format(
                    param[4],
                    "Cn at stall value for positive angle of attack for linear Cn curve",
                )
            )
            f.write(
                "{:<10f}	{:40}".format(
                    param[5],
                    "Cn at stall value for negative angle of attack for linear Cn curve",
                )
            )
            f.write("{:<10f}	{:40}".format(param[6], "Angle of attack for minimum CD (deg)"))
            f.write("{:<10f}	{:40}".format(param[7], "Minimum CD value"))
            for a, cl, cd, cm in zip(p.alpha, p.cl, p.cd, p.cm):
                f.write(f"{a:<10f}	{cl:<10f}	{cd:<10f}	{cm:<10f}")
            f.write("EOT")
        f.close()

    def createDataGrid(self):
        """Create data grid."""
        af = self.interpToCommonAlpha()
        polarList = af.polars

        # angle of attack is already same for each polar
        alpha = polarList[0].alpha

        # all Reynolds numbers
        Re = [p.Re for p in polarList]

        # fill in cl, cd grid
        cl = np.zeros((len(alpha), len(Re)))
        cd = np.zeros((len(alpha), len(Re)))
        cm = np.zeros((len(alpha), len(Re)))

        for idx, p in enumerate(polarList):
            cl[:, idx] = p.cl
            cd[:, idx] = p.cd
            cm[:, idx] = p.cm

        return alpha, Re, cl, cd, cm

    def plot(self, single_figure=True):
        """Plot polars."""
        import matplotlib.pyplot as plt

        figs = []

        # if in single figure mode (default)
        if single_figure:
            # generate figure handles
            fig1 = plt.figure(figsize=(10, 6))
            ax1 = fig1.add_subplot(111)
            figs.append(fig1)

            fig2 = plt.figure(figsize=(10, 6))
            ax2 = fig2.add_subplot(111)
            figs.append(fig2)

            # loop through all polars to see if we need to generate handles for cm figs
            for p in self.polars:
                if np.count_nonzero(p.cm) > 0:
                    fig3 = plt.figure(figsize=(10, 6))
                    ax3 = fig3.add_subplot(111)
                    figs.append(fig3)
                    break

            # loop through polars and plot
            for p in self.polars:
                # plot cl
                ax1.plot(p.alpha, p.cl, label="Re = " + str(p.Re / 1e6) + " million")
                ax1.set_xlabel("angle of attack (deg)")
                ax1.set_ylabel("lift coefficient")
                ax1.legend(loc="best")
                ax1.grid()

                # plot cd
                ax2.plot(p.alpha, p.cd, label="Re = " + str(p.Re / 1e6) + " million")
                ax2.set_xlabel("angle of attack (deg)")
                ax2.set_ylabel("drag coefficient")
                ax2.legend(loc="best")
                ax2.grid()

                # plot cm
                if np.count_nonzero(p.cm) > 0:
                    ax3.plot(p.alpha, p.cm, label="Re = " + str(p.Re / 1e6) + " million")
                    ax3.set_xlabel("angle of attack (deg)")
                    ax3.set_ylabel("moment coefficient")
                    ax3.legend(loc="best")
                    ax3.grid()

        # otherwise, multi figure mode -- plot all on separate figures
        else:
            for p in self.polars:
                fig = plt.figure(figsize=(10, 6))
                figs.append(fig)
                ax = fig.add_subplot(111)
                ax.plot(p.alpha, p.cl, label="Re = " + str(p.Re / 1e6) + " million")
                ax.set_xlabel("angle of attack (deg)")
                ax.set_ylabel("lift coefficient")
                ax.legend(loc="best")
                ax.grid()

                fig = plt.figure(figsize=(10, 6))
                figs.append(fig)
                ax = fig.add_subplot(111)
                ax.plot(p.alpha, p.cd, label="Re = " + str(p.Re / 1e6) + " million")
                ax.set_xlabel("angle of attack (deg)")
                ax.set_ylabel("drag coefficient")
                ax.legend(loc="best")
                ax.grid()

                if np.count_nonzero(p.cm) > 0:
                    fig = plt.figure(figsize=(10, 6))
                    figs.append(fig)
                    ax = fig.add_subplot(111)
                    ax.plot(p.alpha, p.cm, label="Re = " + str(p.Re / 1e6) + " million")
                    ax.set_xlabel("angle of attack (deg)")
                    ax.set_ylabel("moment coefficient")
                    ax.legend(loc="best")
                    ax.grid()

        return figs
